package it.tommy.ded.treasoures.generator.loot.artobjects;

import it.tommy.ded.treasoures.generator.loot.GemsArt;

public enum Art750GP implements GemsArt {
   CALICE_IN_ARGENTO_CON_PIETRE_DI_LUNA("CALICE IN ARGENTO CON PIETRE DI LUNA"),
    SPADA_LUNGA_IN_ACCIAIO_ARGENTATO_CON_GIETTO_SET_NELL_ELSA_ARPA_INTAGLIATA_IN_LEGNO_ESOTICO_CON_INTERNO_IN_AVORIO_E_GEMME_IN_ZIRCONI("SPADA LUNGA IN ACCIAIO ARGENTATO CON GIETTO SET NELL'ELSA ARPA INTAGLIATA IN LEGNO ESOTICO CON INTERNO IN AVORIO E GEMME IN ZIRCONI"),
    ARPA_INTAGLIATA_IN_LEGNO_ESOTICO_CON_INTARSI_IN_AVORIO_E_DI_ZIRCONI("ARPA INTAGLIATA IN LEGNO ESOTICO CON INTARSI IN AVORIO E DI ZIRCONI"),
    PETTINE_DI_DRAGO_CON_GRANATI_ROSSI_COME_OCCHI_TAPPO_DI_BOTTIGLIA_SUGHERO_GOFFRATO_CON_FOGLIA_D_ORO_E_INCASTONATO_CON_UNA_METISTA("PETTINE DI DRAGO CON GRANATI ROSSI COME OCCHI TAPPO DI BOTTIGLIA SUGHERO GOFFRATO CON FOGLIA D'ORO E INCASTONATO CON UNA METISTA"),
    PUGNALE_IN_ELECTRUM_CERIMONIALE_CON_UNA_PERLA_NERA_NEL_POMO("PUGNALE IN ELECTRUM CERIMONIALE CON UNA PERLA NERA NEL POMO"),
    SPILLA_IN_ARGENTO_E_ORO("SPILLA IN ARGENTO E ORO"),
    STATUETTA_DI_OSSIDIANA_CON_RACCORDI_IN_ORO("STATUETTA DI OSSIDIANA CON RACCORDI IN ORO"),
    PICCOLO_IDOLO_D_ORO_MASSICCIO("PICCOLO IDOLO D'ORO MASSICCIO"),
    MASCHERA_DA_GUERRA_DIPINTA_IN_ORO("MASCHERA DA GUERRA DIPINTA IN ORO"),
    CALICE_D_ORO_STOVIGLIE_CON_GEMME_INCASTONATE("CALICE D'ORO/STOVIGLIE CON GEMME INCASTONATE");


    private final String descrizione;
    private final static int GP = 750;
    Art750GP(String descrizione) {
        this.descrizione = descrizione;
    }

    public String getDescrizione(){return descrizione;}
    public int getGp(){return GP;}

    @Override
    public String toString() {
     return GP + ": "+descrizione;
    }


}
